//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string Username { get; set; }
        public string Title { get; set; }
        public string Release_Date { get; set; }
        public string Overview { get; set; }
    
        public virtual User User { get; set; }
    }
}
